version: 0.2
phases:
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pipenv install awscli aws-sam-cli
      - pipenv run sam package --template-file template-dynamo --s3-bucket stephen-code-sam --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml