#SAM FILE
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  helloworldpython3:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app-dynamo.lambda_handler
      Runtime: python3.6
      CodeUri: source/
      Description: A starter AWS Lambda function with API.
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
          REGION_NAME: !Ref AWS::Region
      Events:
        StephenAPI:
          Type: Api
          Properties:
            Path: /peng
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: greeting
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1    